//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodeKeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KodeKeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] connections {
            get {
                object obj = ResourceManager.GetObject("connections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connections1 {
            get {
                object obj = ResourceManager.GetObject("connections1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- MySQL dump 10.16  Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64)
        ///--
        ///-- Host: localhost    Database: db
        ///-- ------------------------------------------------------
        ///-- Server version	10.1.26-MariaDB-0+deb9u1
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        ////*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        ////*!40101 SET NAMES utf8mb4 */;
        ////*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
        ////*!40103 SET TIME_ZON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Example template file
        ///
        ///-MAIN-
        ///PROJECT=test_project
        ///FNAME=baz.pl
        ///FPATH=/foo/bar/
        ///PARAMS=date username
        ///VERSION=1.0
        ///INUSE=1
        ///
        ///-FILE-
        ///PATH=c:\files\foo\bar\baz.pl
        ///IMAGE=perl_1_256
        ///
        ///-COMMENT-
        ///CSTART
        ///Here is a comment... can&apos;t be longer than 300 characters (the rest is trimmed off)
        ///CEND
        ///
        ///-NOTES-
        ///NSTART
        ///The note explaining how the file works, what it&apos;s used for 
        ///and anything else you want to explain
        ///NEND
        ///
        ///-MISC-
        ///RIGHTS=0755
        ///OWNER=admin
        ///GROUP=editors
        ///#CREATED=
        ///#MODIFIED=
        ///
        ///--FILE--
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string file_data_example {
            get {
                return ResourceManager.GetString("file_data_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Main file data
        ///-MAIN-
        ///#Project name
        ///#(eg: weblabel_hu)
        ///PROJECT=
        ///#File Name
        ///#(eg: index.php)
        ///FNAME=
        ///#File Path
        ///#(eg: /usr/local/weblabel_ssl/)
        ///FPATH=
        ///#Input parameters
        ///#(eg: run)
        ///PARAMS=
        ///#File Version
        ///#(eg: v01 or _new)
        ///VERSION=
        ///#Is file in use
        ///#(bool: 0 for false 1 for true)
        ///INUSE=
        ///
        ///#File to attach
        ///-FILE-
        ///#File path
        ///#(eg: c:\foo\bar\index.php)
        ///PATH=
        ///#Image to use if not the default
        ///#(eg: code_2_256)
        ///IMAGE=
        ///
        ///#Comment for the file
        ///#300 character long max
        ///-COMMENT-
        ///#put commen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileDataTemplate {
            get {
                return ResourceManager.GetString("FileDataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] filedb {
            get {
                object obj = ResourceManager.GetObject("filedb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] filedb1 {
            get {
                object obj = ResourceManager.GetObject("filedb1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO images (name, size, for, image) VALUES 
        ///(&apos;code_128&apos;, 128, &apos;code&apos;, &apos;137|80|78|71|13|10|26|10|0|0|0|13|73|72|68|82|0|0|0|128|0|0|0|128|8|6|0|0|0|195|62|97|203|0|0|0|1|115|82|71|66|0|174|206|28|233|0|0|0|4|103|65|77|65|0|0|177|143|11|252|97|5|0|0|0|9|112|72|89|115|0|0|78|188|0|0|78|188|1|161|45|138|240|0|0|0|25|116|69|88|116|83|111|102|116|119|97|114|101|0|119|119|119|46|105|110|107|115|99|97|112|101|46|111|114|103|155|238|60|26|0|0|10|217|73|68|65|84|120|94|237|157|11|140|30|85|21|199|23|159|17|1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageInsert {
            get {
                return ResourceManager.GetString("ImageInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resizer {
            get {
                object obj = ResourceManager.GetObject("resizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_Background_1 {
            get {
                object obj = ResourceManager.GetObject("right_Background_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
